// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// @brief Creates and initializes an isolated native audio player instance.
/// @param config Optional player configuration (NULL for defaults).
/// @param[out] out_result Result status code.
/// @return Pointer to player handle, or NULL on error.
@ffi.Native<
    ffi.Pointer<miniaudio_player_t> Function(
        ffi.Pointer<miniaudio_player_config_t>, ffi.Pointer<ffi.Int32>)>()
external ffi.Pointer<miniaudio_player_t> miniaudio_player_create(
  ffi.Pointer<miniaudio_player_config_t> config,
  ffi.Pointer<ffi.Int32> out_result,
);

/// @brief Uninitializes all nodes, frees audio resources, and destroys the player handle.
/// @param player Player instance handle.
/// @return MAP_SUCCESS on clean termination.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<miniaudio_player_t>)>()
external int miniaudio_player_destroy(
  ffi.Pointer<miniaudio_player_t> player,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<miniaudio_device_info_t>, ffi.Uint32)>()
external void miniaudio_player_free_devices(
  ffi.Pointer<miniaudio_device_info_t> devices,
  int count,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<miniaudio_player_t>)>(isLeaf: true)
external int miniaudio_player_get_bitrate(
  ffi.Pointer<miniaudio_player_t> player,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<miniaudio_player_t>)>(isLeaf: true)
external int miniaudio_player_get_buffer_size(
  ffi.Pointer<miniaudio_player_t> player,
);

@ffi.Native<
    ffi.Int32 Function(ffi.Pointer<miniaudio_player_t>,
        ffi.Pointer<miniaudio_device_info_t>)>(isLeaf: true)
external int miniaudio_player_get_current_device(
  ffi.Pointer<miniaudio_player_t> player,
  ffi.Pointer<miniaudio_device_info_t> out_device,
);

/// ========================================================================= */
/// /* Audio Device Management                                                   */
/// /* =========================================================================
@ffi.Native<
    ffi.Int32 Function(ffi.Pointer<ffi.Pointer<miniaudio_device_info_t>>,
        ffi.Pointer<ffi.Uint32>)>(isLeaf: true)
external int miniaudio_player_get_devices(
  ffi.Pointer<ffi.Pointer<miniaudio_device_info_t>> out_devices,
  ffi.Pointer<ffi.Uint32> out_count,
);

@ffi.Native<ffi.Int64 Function(ffi.Pointer<miniaudio_player_t>)>(isLeaf: true)
external int miniaudio_player_get_duration_ms(
  ffi.Pointer<miniaudio_player_t> player,
);

@ffi.Native<
    ffi.Int32 Function(ffi.Pointer<miniaudio_player_t>,
        ffi.Pointer<miniaudio_player_equalizer_params_t>)>(isLeaf: true)
external int miniaudio_player_get_equalizer(
  ffi.Pointer<miniaudio_player_t> player,
  ffi.Pointer<miniaudio_player_equalizer_params_t> out_equalizer,
);

@ffi.Native<ffi.Int32 Function()>(isLeaf: true)
external int miniaudio_player_get_log_level();

@ffi.Native<ffi.Float Function(ffi.Pointer<miniaudio_player_t>)>(isLeaf: true)
external double miniaudio_player_get_pitch(
  ffi.Pointer<miniaudio_player_t> player,
);

@ffi.Native<ffi.Int64 Function(ffi.Pointer<miniaudio_player_t>)>(isLeaf: true)
external int miniaudio_player_get_position_ms(
  ffi.Pointer<miniaudio_player_t> player,
);

@ffi.Native<ffi.Float Function(ffi.Pointer<miniaudio_player_t>)>(isLeaf: true)
external double miniaudio_player_get_rate(
  ffi.Pointer<miniaudio_player_t> player,
);

/// ========================================================================= */
/// /* Status & Query Inspection                                                 */
/// /* =========================================================================
@ffi.Native<
    ffi.Int32 Function(ffi.Pointer<miniaudio_player_t>,
        ffi.Pointer<miniaudio_player_status_t>)>(isLeaf: true)
external int miniaudio_player_get_status(
  ffi.Pointer<miniaudio_player_t> player,
  ffi.Pointer<miniaudio_player_status_t> out_status,
);

@ffi.Native<ffi.Float Function(ffi.Pointer<miniaudio_player_t>)>(isLeaf: true)
external double miniaudio_player_get_volume(
  ffi.Pointer<miniaudio_player_t> player,
);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<miniaudio_player_t>)>(isLeaf: true)
external int miniaudio_player_is_completed(
  ffi.Pointer<miniaudio_player_t> player,
);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<miniaudio_player_t>)>(isLeaf: true)
external int miniaudio_player_is_playing(
  ffi.Pointer<miniaudio_player_t> player,
);

/// @brief Opens and prepares a local audio file for playback.
/// @param player Player instance handle.
/// @param file_path UTF-8 null-terminated file path.
/// @return MAP_SUCCESS or error code.
@ffi.Native<
    ffi.Int32 Function(
        ffi.Pointer<miniaudio_player_t>, ffi.Pointer<ffi.Char>)>()
external int miniaudio_player_open_file(
  ffi.Pointer<miniaudio_player_t> player,
  ffi.Pointer<ffi.Char> file_path,
);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<miniaudio_player_t>)>()
external int miniaudio_player_pause(
  ffi.Pointer<miniaudio_player_t> player,
);

/// ========================================================================= */
/// /* Playback Controls                                                         */
/// /* =========================================================================
@ffi.Native<ffi.Int32 Function(ffi.Pointer<miniaudio_player_t>)>()
external int miniaudio_player_play(
  ffi.Pointer<miniaudio_player_t> player,
);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<miniaudio_player_t>, ffi.Int64)>()
external int miniaudio_player_seek(
  ffi.Pointer<miniaudio_player_t> player,
  int position_ms,
);

/// ========================================================================= */
/// /* Buffer Size Configuration                                                 */
/// /* =========================================================================
@ffi.Native<ffi.Int32 Function(ffi.Pointer<miniaudio_player_t>, ffi.Uint32)>(
    isLeaf: true)
external int miniaudio_player_set_buffer_size(
  ffi.Pointer<miniaudio_player_t> player,
  int buffer_size_in_frames,
);

@ffi.Native<
    ffi.Int32 Function(
        ffi.Pointer<miniaudio_player_t>, ffi.Pointer<ffi.Char>)>()
external int miniaudio_player_set_device(
  ffi.Pointer<miniaudio_player_t> player,
  ffi.Pointer<ffi.Char> device_id,
);

/// ========================================================================= */
/// /* Equalizer Controls                                                        */
/// /* =========================================================================
@ffi.Native<
    ffi.Int32 Function(ffi.Pointer<miniaudio_player_t>,
        ffi.Pointer<miniaudio_player_equalizer_params_t>)>(isLeaf: true)
external int miniaudio_player_set_equalizer(
  ffi.Pointer<miniaudio_player_t> player,
  ffi.Pointer<miniaudio_player_equalizer_params_t> equalizer,
);

@ffi.Native<
    ffi.Int32 Function(
        ffi.Pointer<miniaudio_player_t>, ffi.Uint32, ffi.Float)>(isLeaf: true)
external int miniaudio_player_set_equalizer_band(
  ffi.Pointer<miniaudio_player_t> player,
  int band_index,
  double gain_db,
);

@ffi.Native<ffi.Void Function(ffi.Int32)>(isLeaf: true)
external void miniaudio_player_set_log_level(
  int level,
);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<miniaudio_player_t>, ffi.Float)>(
    isLeaf: true)
external int miniaudio_player_set_pitch(
  ffi.Pointer<miniaudio_player_t> player,
  double pitch,
);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<miniaudio_player_t>, ffi.Float)>(
    isLeaf: true)
external int miniaudio_player_set_rate(
  ffi.Pointer<miniaudio_player_t> player,
  double rate,
);

/// ========================================================================= */
/// /* Volume, Rate & Pitch Adjustments                                          */
/// /* =========================================================================
@ffi.Native<ffi.Int32 Function(ffi.Pointer<miniaudio_player_t>, ffi.Float)>(
    isLeaf: true)
external int miniaudio_player_set_volume(
  ffi.Pointer<miniaudio_player_t> player,
  double volume,
);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<miniaudio_player_t>)>()
external int miniaudio_player_stop(
  ffi.Pointer<miniaudio_player_t> player,
);

/// ========================================================================= */
/// /* Player Status Snapshot (Single-Call FFI Marshalling)                      */
/// /* =========================================================================
final class miniaudio_device_info_t extends ffi.Struct {
  /// < Unique device ID encoded as hex string, or empty for default
  @ffi.Array.multi([516])
  external ffi.Array<ffi.Char> id;

  /// < Human-readable device name
  @ffi.Array.multi([256])
  external ffi.Array<ffi.Char> name;

  /// < 1 if system default playback device, 0 otherwise
  @ffi.Int32()
  external int is_default;

  /// < 1 if auto (system-managed) routing, 0 for pinned hardware device
  @ffi.Int32()
  external int is_auto;
}

/// ========================================================================= */
/// /* Player Configuration & Callbacks                                          */
/// /* =========================================================================
typedef miniaudio_player_completed_cb
    = ffi.Pointer<ffi.NativeFunction<miniaudio_player_completed_cbFunction>>;
typedef miniaudio_player_completed_cbFunction = ffi.Void Function(
    ffi.Pointer<ffi.Void> user_data);
typedef Dartminiaudio_player_completed_cbFunction = void Function(
    ffi.Pointer<ffi.Void> user_data);

final class miniaudio_player_config_t extends ffi.Struct {
  /// < Sample rate (0 = device native default)
  @ffi.Uint32()
  external int sample_rate;

  /// < Channels (0 = stereo default 2)
  @ffi.Uint32()
  external int channels;

  /// < Buffer period size (0 = default)
  @ffi.Uint32()
  external int period_size_in_frames;

  /// < Optional target device ID (NULL or empty for auto)
  external ffi.Pointer<ffi.Char> playback_device_id;

  /// < Optional completion callback
  external miniaudio_player_completed_cb on_completed;

  /// < Context passed to completion callback
  external ffi.Pointer<ffi.Void> user_data;

  static ffi.Pointer<miniaudio_player_config_t> $allocate(
    ffi.Allocator $allocator, {
    required int sample_rate,
    required int channels,
    required int period_size_in_frames,
    required ffi.Pointer<ffi.Char> playback_device_id,
    required miniaudio_player_completed_cb on_completed,
    required ffi.Pointer<ffi.Void> user_data,
  }) =>
      $allocator<miniaudio_player_config_t>()
        ..ref.sample_rate = sample_rate
        ..ref.channels = channels
        ..ref.period_size_in_frames = period_size_in_frames
        ..ref.playback_device_id = playback_device_id
        ..ref.on_completed = on_completed
        ..ref.user_data = user_data;
}

/// ========================================================================= */
/// /* Equalizer Parameters (10 Bands in dB: -24.0 to +24.0)                     */
/// /* =========================================================================
final class miniaudio_player_equalizer_params_t extends ffi.Struct {
  /// < Low-shelf filter at 60 Hz  (-24.0 to +24.0 dB)
  @ffi.Float()
  external double hz60;

  /// < Peaking filter at 170 Hz   (-24.0 to +24.0 dB)
  @ffi.Float()
  external double hz170;

  /// < Peaking filter at 310 Hz   (-24.0 to +24.0 dB)
  @ffi.Float()
  external double hz310;

  /// < Peaking filter at 600 Hz   (-24.0 to +24.0 dB)
  @ffi.Float()
  external double hz600;

  /// < Peaking filter at 1.0 kHz  (-24.0 to +24.0 dB)
  @ffi.Float()
  external double hz1k;

  /// < Peaking filter at 3.0 kHz  (-24.0 to +24.0 dB)
  @ffi.Float()
  external double hz3k;

  /// < Peaking filter at 6.0 kHz  (-24.0 to +24.0 dB)
  @ffi.Float()
  external double hz6k;

  /// < Peaking filter at 12.0 kHz (-24.0 to +24.0 dB)
  @ffi.Float()
  external double hz12k;

  /// < Peaking filter at 14.0 kHz (-24.0 to +24.0 dB)
  @ffi.Float()
  external double hz14k;

  /// < High-shelf filter at 16.0 kHz (-24.0 to +24.0 dB)
  @ffi.Float()
  external double hz16k;

  static ffi.Pointer<miniaudio_player_equalizer_params_t> $allocate(
    ffi.Allocator $allocator, {
    required double hz60,
    required double hz170,
    required double hz310,
    required double hz600,
    required double hz1k,
    required double hz3k,
    required double hz6k,
    required double hz12k,
    required double hz14k,
    required double hz16k,
  }) =>
      $allocator<miniaudio_player_equalizer_params_t>()
        ..ref.hz60 = hz60
        ..ref.hz170 = hz170
        ..ref.hz310 = hz310
        ..ref.hz600 = hz600
        ..ref.hz1k = hz1k
        ..ref.hz3k = hz3k
        ..ref.hz6k = hz6k
        ..ref.hz12k = hz12k
        ..ref.hz14k = hz14k
        ..ref.hz16k = hz16k;
}

/// ========================================================================= */
/// /* Logging Configuration                                                     */
/// /* =========================================================================
enum miniaudio_player_log_level_t {
  MAP_LOG_LEVEL_NONE(0),
  MAP_LOG_LEVEL_ERROR(1),
  MAP_LOG_LEVEL_WARNING(2),
  MAP_LOG_LEVEL_INFO(3),
  MAP_LOG_LEVEL_DEBUG(4),
  MAP_LOG_LEVEL_VERBOSE(5);

  final int value;
  const miniaudio_player_log_level_t(this.value);

  static miniaudio_player_log_level_t fromValue(int value) => switch (value) {
        0 => MAP_LOG_LEVEL_NONE,
        1 => MAP_LOG_LEVEL_ERROR,
        2 => MAP_LOG_LEVEL_WARNING,
        3 => MAP_LOG_LEVEL_INFO,
        4 => MAP_LOG_LEVEL_DEBUG,
        5 => MAP_LOG_LEVEL_VERBOSE,
        _ => throw ArgumentError(
            'Unknown value for miniaudio_player_log_level_t: $value'),
      };
}

enum miniaudio_player_playback_state_t {
  MAP_PLAYBACK_STATE_STOPPED(0),
  MAP_PLAYBACK_STATE_PLAYING(1),
  MAP_PLAYBACK_STATE_PAUSED(2),
  MAP_PLAYBACK_STATE_COMPLETED(3),
  MAP_PLAYBACK_STATE_BUFFERING(4),
  MAP_PLAYBACK_STATE_ERROR(5);

  final int value;
  const miniaudio_player_playback_state_t(this.value);

  static miniaudio_player_playback_state_t fromValue(int value) =>
      switch (value) {
        0 => MAP_PLAYBACK_STATE_STOPPED,
        1 => MAP_PLAYBACK_STATE_PLAYING,
        2 => MAP_PLAYBACK_STATE_PAUSED,
        3 => MAP_PLAYBACK_STATE_COMPLETED,
        4 => MAP_PLAYBACK_STATE_BUFFERING,
        5 => MAP_PLAYBACK_STATE_ERROR,
        _ => throw ArgumentError(
            'Unknown value for miniaudio_player_playback_state_t: $value'),
      };
}

/// ========================================================================= */
/// /* Error and Status Codes                                                    */
/// /* =========================================================================
enum miniaudio_player_result_t {
  MAP_SUCCESS(0),
  MAP_ERROR_GENERIC(-1),
  MAP_ERROR_INVALID_ARGS(-2),
  MAP_ERROR_OUT_OF_MEMORY(-3),
  MAP_ERROR_ENGINE_INIT(-4),
  MAP_ERROR_FILE_NOT_FOUND(-5),
  MAP_ERROR_DECODE_FAILED(-6),
  MAP_ERROR_INVALID_STATE(-7),
  MAP_ERROR_SEEK_FAILED(-8),
  MAP_ERROR_NODE_FAILED(-9),
  MAP_ERROR_UNSUPPORTED(-10);

  final int value;
  const miniaudio_player_result_t(this.value);

  static miniaudio_player_result_t fromValue(int value) => switch (value) {
        0 => MAP_SUCCESS,
        -1 => MAP_ERROR_GENERIC,
        -2 => MAP_ERROR_INVALID_ARGS,
        -3 => MAP_ERROR_OUT_OF_MEMORY,
        -4 => MAP_ERROR_ENGINE_INIT,
        -5 => MAP_ERROR_FILE_NOT_FOUND,
        -6 => MAP_ERROR_DECODE_FAILED,
        -7 => MAP_ERROR_INVALID_STATE,
        -8 => MAP_ERROR_SEEK_FAILED,
        -9 => MAP_ERROR_NODE_FAILED,
        -10 => MAP_ERROR_UNSUPPORTED,
        _ => throw ArgumentError(
            'Unknown value for miniaudio_player_result_t: $value'),
      };
}

final class miniaudio_player_status_t extends ffi.Struct {
  /// < Current position in milliseconds
  @ffi.Int64()
  external int position_ms;

  /// < Total duration in milliseconds
  @ffi.Int64()
  external int duration_ms;

  /// < 1 if actively playing, 0 if paused/stopped
  @ffi.Int32()
  external int is_playing;

  /// < 1 if buffering, 0 otherwise
  @ffi.Int32()
  external int is_buffering;

  /// < 1 if track completed, 0 otherwise
  @ffi.Int32()
  external int is_completed;

  /// < miniaudio_player_playback_state_t
  @ffi.Int32()
  external int state;

  /// < Current volume (0.0 to 1.0+)
  @ffi.Float()
  external double volume;

  /// < Playback speed multiplier (0.1 to 4.0+)
  @ffi.Float()
  external double rate;

  /// < Pitch multiplier (0.1 to 4.0+)
  @ffi.Float()
  external double pitch;

  /// < Audio bitrate in bits per second (bps)
  @ffi.Uint32()
  external int bitrate;

  /// < Current 10-band equalizer settings
  external miniaudio_player_equalizer_params_t equalizer;

  /// < Currently active audio output device
  external miniaudio_device_info_t device;
}

/// Opaque player handle
typedef miniaudio_player_t = ffi.Opaque;
